// user Login...
export const ADD_USER_IS_PROFILE = 'ADD_USER_IS_PROFILE'
export const ADD_USER_LOADING = 'ADD_USER_LOADING'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_FAIL = 'ADD_USER_FAIL'
export const ADD_LOGIN_RESPONSE = 'ADD_LOGIN_RESPONSE'



// SingUP 
export const ADD_SING_LOADING = 'ADD_SING_LOADING'
export const ADD_SING_SUCCESS = 'ADD_SING_SUCCESS'
export const ADD_SING_FAIL = 'ADD_SING_FAIL'

// UPLOADING... 
export const ADD_UPLOADING_USER_SUCCESS = 'ADD_UPLOADING_USER_SUCCESS'
export const ADD_UPLOADING_USER_FAIL = 'ADD_UPLOADING_USER_FAIL'
// user id 
export const ADD_USER_PROFILE_LOADING = 'ADD_USER_PROFILE_LOADING'
export const ADD_USER_PROFILE_SUCCESCC = 'ADD_USER_PROFILE_SUCCESCC'
export const ADD_USER_PROFILE_FAIL = 'ADD_USER_PROFILE_FAIL'


// userList Friends..
export const ADD_USERLISTS_FRIENDS_LOADING = 'ADD_USERLISTS_FRIENDS_LOADING'
export const ADD_USERLISTS_FRIENDS_SUCCECC = 'ADD_USERLISTS_FRIENDS_SUCCECC'
export const ADD_USERLISTS_FRIENDS_FAIL = 'ADD_USERLISTS_FRIENDS_FAIL'


// IMAGE profil
export const ADD_USER_IMAGE_LOADING = 'ADD_USER_IMAGE_LOADING'
export const ADD_USER_IMAGE_SUCCESS = 'ADD_USER_IMAGE_SUCCESS'
export const ADD_USER_IMAGE_FAIL = 'ADD_USER_IMAGE_FAIL'

// cover profile
export const ADD_USER_COVER_LOADING = 'ADD_USER_COVER_LOADING'
export const ADD_USER_COVER_SUCCESS = 'ADD_USER_COVER_SUCCESS'
export const ADD_USER_COVER_FAIL = 'ADD_USER_COVER_FAIL'

// add address.
export const ADD_USER_ADDRESS_LOADING = 'ADD_USER_ADDRESS_LOADING'
export const ADD_USER_ADDRESS_SUCCESS = 'ADD_USER_ADDRESS_SUCCESS'
export const ADD_USER_ADDRESS_FAIL = 'ADD_USER_ADDRESS_FAIL'


// change Username.... 
export const ADD_USER_USERNAME_LOADING = 'ADD_USER_USERNAME_LOADING'
export const ADD_USER_USERNAME_SUCCESS = 'ADD_USER_USERNAME_SUCCESS'
export const ADD_USER_USERNAME_FAIL = 'ADD_USER_USERNAME_FAIL'



// user list 
export const ADD_USER_LIST_LOADING = 'ADD_USER_LIST_LOADING'
export const ADD_USER_LIST_SUCCESS = 'ADD_USER_LIST_SUCCESS'
export const ADD_USER_LIST_FAIL = 'ADD_USER_LIST_FAIL'


// okej friends.. 
export const ADD_USER_OKEJ_LOADING = 'ADD_USER_OKEJ_LOADING'
export const ADD_USER_OKEJ_SUCCESS = 'ADD_USER_OKEJ_SUCCESS'
export const ADD_USER_OKEJ_FAIL = 'ADD_USER_OKEJ_FAIL'


// SEND fRIND, 
export const ADD_USER_SEND_LOADING = 'ADD_USER_SEND_LOADING'
export const ADD_USER_SEND_SUCCESS = 'ADD_USER_SEND_SUCCESS'
export const ADD_USER_SEND_FAIL = 'ADD_USER_SEND_FAIL'









// show post 
export const ADD_USER_POST_LOADING = 'ADD_USER_POST_LOADING'
export const ADD_USER_POST_SUCCESS = 'ADD_USER_POST_SUCCESS'
export const ADD_USER_POST_FAIL = 'ADD_USER_POST_FAIL'




// create Post.. 
export const ADD_USER_CREATE_POST_LOADING = 'ADD_USER_CREATE_POST_LOADING'
export const ADD_USER_CREATE_POST_SUCCESS = 'ADD_USER_CREATE_POST_SUCCESS'
export const ADD_USER_CREATE_POST_FAIL = 'ADD_USER_CREATE_POST_FAIL'

// remove post.. from User.. 
export const ADD_POST_REMOVE_LOADING = 'ADD_POST_REMOVE_LOADING'
export const ADD_POST_REMOVE_SUCCESS = 'ADD_POST_REMOVE_SUCCESS'
export const ADD_POST_REMOVE_FAIL = 'ADD_POST_REMOVE_FAIL'


// only post user 
export const ADD_POST_ONLY_USER_LOADIG = 'ADD_POST_ONLY_USER_LOADIG'
export const ADD_POST_ONLY_USER_SUCCESS = 'ADD_POST_ONLY_USER_SUCCESS'
export const ADD_POST_ONLY_USER_FAIL = 'ADD_POST_ONLY_USER_FAIL'


// Update post...

export const ADD_POST_UPDATE_LOADING = 'ADD_POST_UPDATE_LOADING'
export const ADD_POST_UPDATE_SUCCESS = 'ADD_POST_UPDATE_SUCCESS'
export const ADD_POST_UPDATE_FAILT = 'ADD_POST_UPDATE_FAILT'


// add comment ... 
export const ADD_USER_COMMENT_LOADING = 'ADD_USER_COMMENT_LOADING'
export const ADD_USER_COMMENT_SUCCESS = 'ADD_USER_COMMENT_SUCCESS'
export const ADD_USER_COMMENT_FAIL = 'ADD_USER_COMMENT_FAIL'

// remove comment 
export const ADD_COMMENT_REMOVE_LOADING = 'ADD_COMMENT_REMOVE_LOADING'
export const ADD_COMMENT_REMOVE_SUCCESS = 'ADD_COMMENT_REMOVE_SUCCESS'
export const ADD_COMMENT_REMOVE_FAIL = 'ADD_COMMENT_REMOVE_FAIL'



// Like ... 
export const ADD_LIKE_LOAGING = 'ADD_LIKE_LOAGING'
export const ADD_LIKE_SUCCESS = 'ADD_LIKE_SUCCESS'
export const ADD_LIKE_FAIL = 'ADD_LIKE_FAIL'

// VIEWS USER LIKE,,,
export const ADD_LIKE_USER_SUCCESS = 'ADD_LIKE_USER_SUCCESS'
export const ADD_LIKE_USER_FAIL = 'ADD_LIKE_USER_FAIL'


// DELETE fRINDS
export const ADD_USER_FRINDS_SUCCESS = 'ADD_USER_FRINDS_SUCCESS'
export const ADD_USER_FRINDS_FAIL = 'ADD_USER_FRINDS_FAIL'
export const ADD_USER_FRINDS_LOADING = 'ADD_USER_FRINDS_LOADING'


// all list friend to use..
export const ADD_USER_FRIENDS_SUCCESS = 'ADD_USER_FRIENDS_SUCCESS'
export const ADD_USER_FRIENDS_FAIL = 'ADD_USER_FRIENDS_FAIL'


// LIST USER 
export const ADD_LIST_USERS_SUCCESS = 'ADD_LIST_USERS_SUCCESS'
export const ADD_LIST_USERS_FAIL = 'ADD_LIST_USERS_FAIL'



export const ADD_STORY_SUCCESS = 'ADD_STORY_SUCCESS'
export const ADD_STORY_FAIL = 'ADD_STORY_FAIL'

export const ADD_STORY_SHOW_SUCCESS = 'ADD_STORY_SHOW_SUCCESS'
export const ADD_STORY_SHOW_FAIL = 'ADD_STORY_SHOW_FAIL'





// chat user... 
export const ADD_CREATE_CHAT_SUCCESS = 'ADD_CREATE_CHAT_SUCCESS'
export const ADD_CREATE_CHAT_FAIL = 'ADD_CREATE_CHAT_FAIL'



export const ADD_SHOW_CHAT_SUCCESS = 'ADD_SHOW_CHAT_SUCCESS'
export const ADD_SHOW_CHAT_FAIL = 'ADD_SHOW_CHAT_FAIL'


// post id...
export const ADD_POST_ID_SUCCESS = 'ADD_POST_ID_SUCCESS'
export const ADD_POST_ID_FAIL = 'ADD_POST_ID_FAIL'